name: 트러블슈팅 경험 공유
description: 발생한 문제와 해결 방법을 기록하여 공유하는 템플릿입니다.
labels: ["trouble-shooting", "FE"]

body:
  - type: markdown
    attributes:
      name: 연관된 이슈
      description: 'ex) #이슈번호, #이슈번호'
      
  - type: textarea
    attributes:
      name: 수정 내용
      description: '문제 해결을 위해 수정한 부분을 간략히 설명해주세요.'
      placeholder: '예시: `!e.nativeEvent.isComposing` 한 줄을 추가하여 해결.'
      
  - type: textarea
    attributes:
      name: 문제 상황
      description: '문제가 발생한 상황을 간략히 설명해주세요.'
      placeholder: '예시: API 호출 시 CORS 오류가 발생하거나, 데이터베이스 연결 문제 등이 있을 수 있습니다.'
      
  - type: textarea
    attributes:
      name: 해결 방법
      description: '문제를 해결한 방법을 구체적으로 작성해주세요.'
      placeholder: '예시: CORS 설정을 수정하거나, 데이터베이스 연결 문자열을 업데이트한 방법 등을 설명합니다.'
      
  - type: textarea
    attributes:
      name: 스크린샷 (선택)
      description: '해결 과정이나 결과를 보여주는 스크린샷을 첨부해 주세요.'
      placeholder: '스크린샷을 첨부하거나, 필요시 설명을 추가해주세요.'
      
  - type: textarea
    attributes:
      name: 추가 정보 (선택)
      description: '문제 해결에 도움이 되었던 자료나 참고한 문서, 실수한 부분 등을 추가로 작성해 주세요.'
      placeholder: '추가로 참고할 수 있는 링크나 문서, 조언 등을 적어주세요.'
