#1
name: Frontend Main CD Pipeline
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:  # 여기에서 설정 시 전체 step에 자동 적용됨
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ap-northeast-2
    steps:
      - name: Download dist.zip from S3
        run: |
          aws s3 cp s3://${{ secrets.AWS_S3_BUCKET_NAME }}/${{ secrets.AWS_S3_UPLOAD_PREFIX_PROD }}dist.zip dist.zip
          unzip dist.zip -d dist

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_PROD }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.GCP_VM_DOMAIN_PROD }} >> ~/.ssh/known_hosts

      - name: Deploy build files
        run: |
          ssh ${{ secrets.GCP_VM_USER_PROD }}@${{ secrets.GCP_VM_DOMAIN_PROD }} "rm -rf /home/${{ secrets.GCP_VM_USER_PROD }}/fe && mkdir -p /home/${{ secrets.GCP_VM_USER_PROD }}/fe"
          scp -r dist/*/* ${{ secrets.GCP_VM_USER_PROD }}@${{ secrets.GCP_VM_DOMAIN_PROD }}:/home/${{ secrets.GCP_VM_USER_PROD }}/fe

      - name: Setup Nginx and Configure Site
        run: |
          ssh ${{ secrets.GCP_VM_USER_PROD }}@${{ secrets.GCP_VM_DOMAIN_PROD }} 'sudo apt update && sudo apt install -y nginx && \
          sudo rm -f /etc/nginx/sites-available/default && \
          sudo rm -f /etc/nginx/sites-enabled/default && \
          sudo chmod o+x /home/${{ secrets.GCP_VM_USER_PROD }} && \
          sudo chmod o+x /home/${{ secrets.GCP_VM_USER_PROD }}/fe && \
          echo "server {" | sudo tee /etc/nginx/sites-available/myapp.conf && \
          echo "  listen 443 ssl;" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "  server_name ${{ secrets.GCP_VM_DOMAIN_PROD }};" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "  ssl_certificate /etc/letsencrypt/live/${{ secrets.GCP_VM_DOMAIN_PROD }}/fullchain.pem;" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "  ssl_certificate_key /etc/letsencrypt/live/${{ secrets.GCP_VM_DOMAIN_PROD }}/privkey.pem;" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "  location /api/ {" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "    proxy_pass http://localhost:8080/api/;" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "    proxy_http_version 1.1;" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "    proxy_set_header Host \$host;" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "    proxy_set_header X-Real-IP \$remote_addr;" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "    proxy_set_header X-Forwarded-Proto \$scheme;" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "  }" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "  location /api-docs {" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "    proxy_pass http://localhost:8080/api-docs;" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "    proxy_set_header Host \$host;" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "  }" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "  location /swagger-ui/ {" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "    proxy_pass http://localhost:8080/swagger-ui/;" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "    proxy_http_version 1.1;" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "    proxy_set_header Host \$host;" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "    proxy_set_header X-Real-IP \$remote_addr;" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "    proxy_set_header X-Forwarded-Proto \$scheme;" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "  }" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "  location / {" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "    root /home/${{ secrets.GCP_VM_USER_PROD }}/fe;" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "    index index.html index.htm;" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "    try_files \$uri \$uri/ /index.html;" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "  }" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "}" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "server {" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "  listen 80;" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "  server_name ${{ secrets.GCP_VM_DOMAIN_PROD }};" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "  return 301 https://\$host\$request_uri;" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          echo "}" | sudo tee -a /etc/nginx/sites-available/myapp.conf && \
          sudo ln -sf /etc/nginx/sites-available/myapp.conf /etc/nginx/sites-enabled/myapp.conf && \
          sudo nginx -t && sudo systemctl restart nginx'

      - name: Smoke Test after Deployment
        run: |
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://${{ secrets.GCP_VM_DOMAIN_PROD }})
          if [ "$STATUS_CODE" -ne 200 ]; then
              echo "Smoke test failed: / returned $STATUS_CODE"
              exit 1
          fi
