name: Deploy React App to Prod S3

on:
  push:
    branches: [main]          # 필요 시 main 등으로 교체

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{secrets.AWS_REGION}}     # AWS CLI 기본 리전

    steps:
    # 1) 소스 체크아웃
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2) Node.js 설치
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '23.11.0'      # 프로젝트 버전에 맞춰 변경

    # 3) Infisical CLI로 .env 생성
    - name: Fetch environment variables from Infisical
      env:
        INFISICAL_ENV:           ${{ secrets.INFISICAL_ENV_PROD }}
        INFISICAL_PROJECT_ID:    ${{ secrets.INFISICAL_PROJECT_ID }}
        INFISICAL_TOKEN:         ${{ secrets.INFISICAL_TOKEN_PROD }}
        INFISICAL_API_URL:       ${{ secrets.INFISICAL_API_URL }}
        INFISICAL_CLOUDFRONT:    ${{ secrets.AWS_CLOUDFRONT_URL }}
      run: |
        echo "⬇️  Downloading Infisical CLI..."
        curl -Ls https://${INFISICAL_CLOUDFRONT}/tools/infisical-linux-amd64 -o infisical
        chmod +x infisical
        echo "🔐 Exporting secrets to .env..."
        ./infisical export \
          --env=$INFISICAL_ENV \
          --projectId=$INFISICAL_PROJECT_ID \
          --token=$INFISICAL_TOKEN \
          --format=dotenv \
          --domain=$INFISICAL_API_URL > .env
        # 필요하다면 `set -a && source .env && set +a` 로 환경변수 export 가능

    # 4) 의존성 설치
    - name: Install Dependencies
      run: npm ci                # npm install 대신 ci 사용 권장

    # 5) 빌드 (env 로드 완료 상태)
    - name: Build React App
      run: npm run build         # 빌드 결과물은 dist/ 에 생성된다고 가정

    # 6) AWS 자격 증명 설정
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID_S3_FE }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_S3_FE }}
        aws-region:            ${{ env.AWS_REGION }}

    # 7) S3 동기화 (dist/ 내부만)
    - name: Sync to S3
      run: aws s3 sync dist/ s3://${{ secrets.S3_BUCKET_NAME_FE }} --delete

    # 8) CloudFront 캐시 무효화
    - name: Invalidate CloudFront Cache
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_FE }} \
          --paths "/*"
