name: Deploy React App to S3

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '23.11.0'

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_S3_FE }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_S3_FE }}
          aws-region: ap-northeast-2

      - name: Sync to S3
        run: aws s3 sync build/ s3://${{ secrets.S3_BUCKET_NAME_FE }} --delete

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_FE }} \
            --paths "/*"
