name: Frontend CI/CD

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Test
      run: npm test

  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Deploy
      if: github.ref == 'refs/heads/dev'
      env:
        GCP_VM_USER: ${{ secrets.GCP_VM_USER }}
        GCP_VM_IP: ${{ secrets.GCP_VM_IP }}
      run: |
        # 프론트엔드 빌드 파일을 VM으로 복사
        scp -r dist/* $GCP_VM_USER@$GCP_VM_IP:/home/deploy/be/src/main/resources/static/
