name: Dev에서 Main으로만 PR 가능하게 제한

on:
  pull_request:
    branches:
      - main

jobs:
  check-pr:
    if: github.head_ref != 'dev'
    runs-on: ubuntu-latest
    steps:
      - name: dev 외 브랜치에서 PR 시 실패 처리
        run: |
          echo "ERROR: Pull request는 반드시 dev 브랜치에서만 main 브랜치로 가능합니다!"
          exit 1