name: Set reviewers based on branch

# PR이 열리거나, 커밋이 추가되거나, 닫힌 PR이 다시 열릴 때마다 실행
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  set-reviewers:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # PR에 리뷰어를 추가할 수 있는 권한을 부여

    steps:
      # feature to dev로 PR 올라왔을 때
      - name: feature에서 dev로 PR 올라올 때 FullStack팀으로 리뷰어 설정 
        if: github.base_ref == 'dev' && github.head_ref != 'main'
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"reviewers":["@100-hours-a-week/NewSum_FullStack"]}' \
          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers
      
      # dev to main으로 PR 올라왔을 때
      - name: dev에서 main으로 PR 올라올 때 전체 팀으로 리뷰어 설정
        if: github.base_ref == 'main' && github.head_ref == 'dev'
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"reviewers":["@100-hours-a-week/17"]}' \
          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers
