name: Set reviewers based on branch

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  set-reviewers:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write  # PR에 리뷰어를 추가할 수 있는 권한을 부여

    steps:
      # feature to dev로 PR 올라왔을 때
      # - name: feature에서 dev로 PR 올라올 때 FullStack팀으로 리뷰어 설정 
        # if: github.base_ref == 'dev' && github.head_ref != 'main'
        # run: |
          # GitHub 조직에 속한 팀 목록을 가져오기
          # teams=$(curl -s -H "Authorization: token ${{ secrets.REVIEW_TOKEN }}" \
          # https://api.github.com/orgs/100-hours-a-week/teams | jq -r '.[].slug')

          # whole_team=$(curl -s -H "Authorization: token ${{ secrets.REVIEW_TOKEN }}" \
            # https://api.github.com/orgs/100-hours-a-week/teams | jq -r '.[] | select(.slug == "17") | .slug')
          # fullstack_team=$(curl -s -H "Authorization: token ${{ secrets.REVIEW_TOKEN }}" \
            # https://api.github.com/orgs/100-hours-a-week/teams/17/teams | jq -r '.[] | select(.slug == "newsum_fullstack") | .slug')

      - name: Select FullStack Team Members as Reviewers
        id: select-fullstack-reviewers
        run: |
          # 'newsum_fullstack' 팀의 멤버 목록을 가져옵니다.
          fullstack_members=$(curl -s -H "Authorization: token ${{ secrets.REVIEW_TOKEN }}" \
            https://api.github.com/orgs/100-hours-a-week/teams/newsum_fullstack/members | jq -r '.[].login')
      
          # 멤버 목록을 배열로 저장합니다.
          member_array=($fullstack_members)
      
          # 멤버들을 PR 리뷰어로 추가할 수 있도록, 배열에서 리뷰어 이름을 설정합니다.
          reviewer_list=""
          for member in "${member_array[@]}"; do
            reviewer_list+="\"@$member\","
          done
      
          # 마지막 쉼표를 제거합니다.
          reviewer_list=${reviewer_list%,}
      
          # JSON 형식으로 변환된 리뷰어 목록을 출력합니다.
          echo "Reviewers: [$reviewer_list]"
          echo "::set-output name=reviewers::[$reviewer_list]"
      
      - name: Add FullStack Team Members as Reviewers to PR
        run: |
          # PR 번호를 가져옵니다.
          pr_number=${{ github.event.pull_request.number }}
          reviewers=${{ steps.select-fullstack-reviewers.outputs.reviewers }}
      
          # 팀 멤버들을 PR에 리뷰어로 추가합니다.
          curl -s -X POST -H "Authorization: token ${{ secrets.REVIEW_TOKEN }}" \
            -d "{\"reviewers\":$reviewers}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number/requested_reviewers"


      # dev to main으로 PR 올라왔을 때
      - name: dev에서 main으로 PR 올라올 때 전체 팀으로 리뷰어 설정
        if: github.base_ref == 'main' && github.head_ref == 'dev'
        run: |
          # GitHub 조직에 속한 팀 목록을 가져오기
          teams=$(curl -s -H "Authorization: token ${{ secrets.REVIEW_TOKEN }}" \
          https://api.github.com/orgs/100-hours-a-week/teams | jq -r '.[].slug')
          
          echo "Teams: $teams"  # 팀 목록 출력
          
          # 전체 팀을 리뷰어로 설정
          curl -X POST -H "Authorization: token ${{ secrets.REVIEW_TOKEN }}" \
          -d "{\"reviewers\": [\"@100-hours-a-week/17\"]}" \
          https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers
